apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: rconway
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager
      version: "v1.4.0"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: rconway
      interval: 1m
  install:
    crds: "CreateReplace"
    createNamespace: true
  values: {}
